<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>feeditems</name>
   <tag></tag>
   <elementGuidId>b3515898-df37-4a6e-9f83-c81ed8d8de0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//cnv-feed-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//cnv-feed-item</value>
   </webElementProperties>
</WebElementEntity>
